/**
 * CBSE Class 10 Chapter Data
 * Complete syllabus mapping for all subjects separated for Customise Test.
 */

export const CBSE_SUBJECTS = [
  "Mathematics Basic",
  "Mathematics Standard",
  "Physics",
  "Chemistry",
  "Biology",
  "History",
  "Geography",
  "Civics",
  "Economics",
  "English",
  "Information Technology",
  "Artificial Intelligence",
];

export const CBSE_CHAPTERS: Record<string, string[]> = {
  Physics: [
    "Light - Reflection and Refraction",
    "The Human Eye and the Colourful World",
    "Electricity",
    "Magnetic Effects of Electric Current",
  ],
  Chemistry: [
    "Chemical Reactions and Equations",
    "Acids, Bases and Salts",
    "Metals and Non-metals",
    "Carbon and its Compounds",
  ],
  Biology: [
    "Life Processes",
    "Control and Coordination",
    "How do Organisms Reproduce?",
    "Heredity",
    "Our Environment",
  ],
  "Mathematics Basic": [
    "Real Numbers",
    "Polynomials",
    "Pair of Linear Equations in Two Variables",
    "Quadratic Equations",
    "Arithmetic Progressions",
    "Triangles",
    "Coordinate Geometry",
    "Introduction to Trigonometry",
    "Some Applications of Trigonometry",
    "Circles",
    "Areas Related to Circles",
    "Surface Areas and Volumes",
    "Statistics",
    "Probability",
  ],
  "Mathematics Standard": [
    "Real Numbers",
    "Polynomials",
    "Pair of Linear Equations in Two Variables",
    "Quadratic Equations",
    "Arithmetic Progressions",
    "Triangles",
    "Coordinate Geometry",
    "Introduction to Trigonometry",
    "Some Applications of Trigonometry",
    "Circles",
    "Areas Related to Circles",
    "Surface Areas and Volumes",
    "Statistics",
    "Probability",
  ],
  History: [
    "The Rise of Nationalism in Europe",
    "Nationalism in India",
    "The Making of a Global World",
    "Print Culture and the Modern World",
    "Map Pointing - History",
  ],
  Geography: [
    "Resources and Development",
    "Forest and Wildlife Resources",
    "Water Resources",
    "Agriculture",
    "Minerals and Energy Resources",
    "Manufacturing Industries",
    "Lifelines of National Economy",
    "Map Pointing - Geography",
  ],
  "Civics": [
    "Power-sharing",
    "Federalism",
    "Gender, Religion and Caste",
    "Political Parties",
    "Outcomes of Democracy",
  ],
  Economics: [
    "Development",
    "Sectors of the Indian Economy",
    "Money and Credit",
    "Globalisation and the Indian Economy",
    "Consumer Rights",
  ],
  English: [
    "A Letter to God",
    "Nelson Mandela - Long Walk to Freedom",
    "Stories About Flying",
    "From the Diary of Anne Frank",
    "Glimpses of India",
    "Mijbil the Otter",
    "Madam Rides the Bus",
    "The Sermon at Benares",
    "The Proposal",
    "Dust of Snow",
    "Fire and Ice",
    "A Tiger in the Zoo",
    "The Ball Poem",
    "Amanda!",
    "The Tale of Custard the Dragon",
    "For Anne Gregory",
    "A Triumph of Surgery",
    "The Thief's Story",
    "The Midnight Visitor",
    "A Question of Trust",
    "Footprints Without Feet",
    "The Making of a Scientist",
    "The Necklace",
    "Bholi",
    "The Book that Saved the Earth",
    "Grammar - Determiners",
    "Grammar - Editing",
    "Grammar - Gap Filling",
    "Grammar - Modals",
    "Grammar - Phrasal Verbs",
    "Grammar - Punctuation",
    "Grammar - Reported Speech",
    "Grammar - Subject-Verb Concord",
    "Grammar - Tenses",
    "Grammar - Transformation",
  ],
  "Information Technology": [
    "Digital Documentation (Writer)",
    "Electronic Spreadsheet (Calc)",
    "Database Management System (Base)",
    "Internet and Workplace Safety",
  ],
  "Artificial Intelligence": [
    "Revisiting AI Project Cycle & Ethical Frameworks for AI",
    "Natural Language Processing",
    "Computer Vision",
    "Evaluating Models",
    "Advanced Concepts of Modeling in AI",
    "Statistical Data",
    "Employability Skills - Communication Skills",
    "Employability Skills - Self-management Skills",
    "Employability Skills - ICT Skills",
    "Employability Skills - Entrepreneurial Skills",
    "Employability Skills - Green Skills",
  ],
};
