/**
 * CBSE Class 10 Chapter Data
 * Complete syllabus mapping for all subjects
 */

export const ICSE_SUBJECTS = [
  "Science",
  "Mathematics Basic",
  "Mathematics Standard",
  "Social Science",
  "English",
  "Information Technology",
  "Artificial Intelligence",
];

export const ICSE_CHAPTERS: Record<string, string[]> = {
  Science: [
    // Physics chapters
    "FORCE, WORK, POWER AND ENERGY",
    "LIGHT - REFRACTION AND LENSES",
    "SOUND",
    "ELECTRICITY AND MAGNETISM",
    "HEAT AND CALORIMETRY",
    "MODERN PHYSICS - RADIOACTIVITY",
    "MACHINES AND LEVERS",
    "ELECTROMAGNETISM",
    "HOUSEHOLD CIRCUITS",
    // Chemistry chapters
    "PERIODIC TABLE - PERIODIC PROPERTIES",
    "CHEMICAL BONDING",
    "STUDY OF ACIDS, BASES AND SALTS",
    "ANALYTICAL CHEMISTRY",
    "MOLE CONCEPT AND STOICHIOMETRY",
    "ELECTROLYSIS",
    "METALLURGY",
    "STUDY OF COMPOUNDS - HYDROGEN",
    "STUDY OF COMPOUNDS - AMMONIA",
    "STUDY OF COMPOUNDS - NITRIC ACID",
    "STUDY OF COMPOUNDS - SULPHURIC ACID",
    "ORGANIC CHEMISTRY - HYDROCARBONS",
    "ORGANIC CHEMISTRY - ALCOHOLS AND CARBOXYLIC ACIDS",
    "ALLOYS",
    "PRACTICAL CHEMISTRY",
    "MOLE CONCEPT - EMPIRICAL AND MOLECULAR FORMULA",
    // Biology chapters
    "Cell Cycle, Cell Division and Structure of Chromosomes",
    "Genetics - Mendel's Laws and Inheritance",
    "Absorption by Roots and Osmosis",
    "Transpiration and Photosynthesis",
    "Photosynthesis",
    "Plant Physiology",
    "The Endocrine System",
    "Reproductive System",
    "Population and Health",
    "Pollution and Waste Management",
    "Human Evolution",
  ],
  "Mathematics Basic": [
    "Real Numbers",
    "Polynomials",
    "Pair of Linear Equations in Two Variables",
    "Quadratic Equations",
    "Arithmetic Progressions",
    "Triangles",
    "Coordinate Geometry",
    "Introduction to Trigonometry",
    "Some Applications of Trigonometry",
    "Circles",
    "Areas Related to Circles",
    "Surface Areas and Volumes",
    "Statistics",
    "Probability",
  ],
  "Mathematics Standard": [
    "Real Numbers",
    "Polynomials",
    "Pair of Linear Equations in Two Variables",
    "Quadratic Equations",
    "Arithmetic Progressions",
    "Triangles",
    "Coordinate Geometry",
    "Introduction to Trigonometry",
    "Some Applications of Trigonometry",
    "Circles",
    "Areas Related to Circles",
    "Surface Areas and Volumes",
    "Statistics",
    "Probability",
  ],
  "Social Science": [
    "History",
    "Geography",
    "Political Science",
    "Economics",
  ],
  English: [
    "A Letter to God",
    "Nelson Mandela - Long Walk to Freedom",
    "Stories About Flying",
    "From the Diary of Anne Frank",
    "Glimpses of India",
    "Mijbil the Otter",
    "Madam Rides the Bus",
    "The Sermon at Benares",
    "The Proposal",
    "Dust of Snow",
    "Fire and Ice",
    "A Tiger in the Zoo",
    "The Ball Poem",
    "Amanda!",
    "The Tale of Custard the Dragon",
    "For Anne Gregory",
    "A Triumph of Surgery",
    "The Thief's Story",
    "The Midnight Visitor",
    "A Question of Trust",
    "Footprints Without Feet",
    "The Making of a Scientist",
    "The Necklace",
    "Bholi",
    "The Book that Saved the Earth",
    "Grammar - Determiners",
    "Grammar - Editing",
    "Grammar - Gap Filling",
    "Grammar - Modals",
    "Grammar - Phrasal Verbs",
    "Grammar - Punctuation",
    "Grammar - Reported Speech",
    "Grammar - Subject-Verb Concord",
    "Grammar - Tenses",
    "Grammar - Transformation",
  ],
  "Information Technology": [
    "Digital Documentation (Writer)",
    "Electronic Spreadsheet (Calc)",
    "Database Management System (Base)",
    "Internet and Workplace Safety",
  ],
  "Artificial Intelligence": [
    "Revisiting AI Project Cycle & Ethical Frameworks for AI",
    "Natural Language Processing",
    "Computer Vision",
    "Evaluating Models",
    "Advanced Concepts of Modeling in AI",
    "Statistical Data",
    "Employability Skills - Communication Skills",
    "Employability Skills - Self-management Skills",
    "Employability Skills - ICT Skills",
    "Employability Skills - Entrepreneurial Skills",
    "Employability Skills - Green Skills",
  ],
};
